# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres:postgres@localhost:5432/boilerplate_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_TEST_URL', 'postgres://postgres:postgres@localhost:5432/boilerplate_test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 2
  checkout_timeout: 5
  variables:
    statement_timeout: 5000
